import mongoose from "mongoose";

const reportSchema = new mongoose.Schema({
  targetApplication: {
    type: String,
    enum: [
      "juice-shop",
      "dvwa",
      "webgoat",
      "vulnhub",
      "tryhackme",
      "hackthebox",
      "portswigger",
      "cloudgoat",
      "ctflearn",
      "root-me",
      "bodgeit",
      "mutillidae",
      "nodegoat",
      "security-shepherd",
      "api-lab",
      "cryptopalace",
      "overflow",
      "csrf-lab",
      "xxe-lab",
      "idor-lab",
      "jwt-lab",
      "oauth-lab",
      "sqli-lab",
      "ssrf-lab",
      "xss-game",
      "websocket-lab",
      "docker-breakout",
      "k8s-hack-lab",
      "reverseme",
      "android-crackme",
      "ios-crackme",
      "cloud-hackthebox",
      "forensics-lab",
      "pwnable",
      "binary-exploit",
      "mobile-security",
      "injection-hunt",
      "crypto-vault",
      "oscp-lab",
      "pentesterlab",
      "sandbox-escape",
      "privilege-escalation",
      "misconfiguration",
      "ssti-lab",
      "dns-exfil",
      "cloud-misconf",
      "malware-analysis",
      "c2-lab",
      "web-hackthebox",
      "thm-vulnnet",
    ],
    required: true,
  },
  severity: {
    type: String,
    enum: ["Low", "Medium", "High", "Critical"],
    required: true,
  },
  vulnerabilityTitle: {
    type: String,
    required: true,
  },
  detailedDescription: {
    type: String,
    required: true,
  },
  impactAssessment: {
    type: String,
    required: true,
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User", // assuming your user model is named "User"
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

const Report = mongoose.model("Report", reportSchema);

export default Report;
